#docker run -d -v ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
# docker exec -it ollama ollama run phi3.5
# Pull model from console: docker exec -it ollama-ollama-1 ollama pull qwen:1.8b

services:
  webui:
    image: ghcr.io/open-webui/open-webui:git-09a81eb
    expose:
      - 8080/tcp
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    restart: always

  ollama:
    image: ollama/ollama
    expose:
      - 11434/tcp
    ports:
      - "11434:11434"
    healthcheck:
      test: ollama --version || exit 1
    entrypoint: /root/entrypoint.sh
    volumes:
      - ./data:/root/.ollama
      - ./entrypoint.sh:/root/entrypoint.sh
    restart: always
